// Two honesty artifacts in one collapsible panel:
//   1. The anti-hardcode profile tests — each scripted student run headless through the full
//      pipeline, asserting the diagnosis matches its expected column. PASS/FAIL rendered live.
//   2. Model validation on a clearly-labeled SYNTHETIC cohort: held-out next-answer AUC / accuracy
//      / Brier for BKT vs baselines. Real computed numbers, seeded so they don't jitter.

import { useMemo } from 'react';
import { DEMO_PROFILES } from '../data/demoProfiles.js';
import { toObservation } from '../data/questions.js';
import { diagnose } from '../engine/diagnosis.js';
import { runValidation } from '../engine/validation.js';
import { skillName } from '../data/skills.js';

export default function ValidationPanel({ skillIds, graph, hypotheses, params }) {
  const tests = useMemo(
    () =>
      DEMO_PROFILES.map((p) => {
        const obs = p.answers.map(([q, c]) => toObservation(q, c));
        const d = diagnose(obs, skillIds, graph, { hypotheses, params });
        const pass =
          p.expected === 'insufficient' ? !d.sufficient : d.sufficient && d.keystone === p.expected;
        const got = d.sufficient ? skillName(d.keystone) : 'insufficient evidence';
        return { id: p.id, label: p.label, expected: p.expected, got, pass };
      }),
    [skillIds, graph, hypotheses, params],
  );

  const val = useMemo(() => runValidation(skillIds, params), [skillIds, params]);
  const models = [val.models.bkt, val.models.previousAnswer, val.models.majority];
  const bestAuc = Math.max(...models.map((m) => m.auc));

  return (
    <div className="panel wide">
      <details className="collapsible">
        <summary>Automated tests &amp; model validation</summary>

        <h2 style={{ marginTop: 16 }}>Demo-profile tests <span className="layer-tag">· anti-hardcode proof</span></h2>
        {tests.map((t) => (
          <div className="test-row" key={t.id}>
            <span className={`test-badge ${t.pass ? 'pass' : 'fail'}`}>{t.pass ? 'PASS' : 'FAIL'}</span>
            <span><b>Profile {t.id}</b> → {t.got}</span>
            <span className="exp">expected: {t.expected === 'insufficient' ? 'insufficient evidence' : skillName(t.expected)}</span>
          </div>
        ))}

        <h2 style={{ marginTop: 20 }}>
          Model validation <span className="synthetic-flag">synthetic cohort — not real students</span>
        </h2>
        <table className="val">
          <thead>
            <tr><th>Model</th><th>AUC</th><th>Accuracy</th><th>Brier ↓</th></tr>
          </thead>
          <tbody>
            {models.map((m) => (
              <tr key={m.name} className={m.auc === bestAuc ? 'best' : ''}>
                <td>{m.name}</td>
                <td>{m.auc.toFixed(3)}</td>
                <td>{m.accuracy.toFixed(3)}</td>
                <td>{m.brier.toFixed(3)}</td>
              </tr>
            ))}
          </tbody>
        </table>
        <p className="val-note">
          {val.nHeldout.toLocaleString()} held-out predictions from {val.nStudents.toLocaleString()} simulated
          students generated by the misconception model. This measures calibration on synthetic data, not
          real-world accuracy — the ASSISTments held-out evaluation lives in <span className="mono">evaluation/</span>.
        </p>
      </details>
    </div>
  );
}
